Traceback (most recent call last):
  File "/Users/stratismarkou/miniconda3/envs/rw/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/stratismarkou/miniconda3/envs/rw/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/stratismarkou/miniconda3/envs/rw/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/stratismarkou/miniconda3/envs/rw/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/stratismarkou/miniconda3/envs/rw/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/stratismarkou/miniconda3/envs/rw/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/stratismarkou/miniconda3/envs/rw/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from automata.fa.dfa import DFA

A = "A"
B = "B"
C = "C"

dfa = DFA(
    states={A, B, C},
    input_symbols=(0, 1),
    transitions={
        A: {0: A, 1: B},
        B: {0: A, 1: C},
        C: {0: C, 1: C},
    },
    initial_state=A,
    final_states={C,},
)

dfa.show_diagram()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mautomata[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfa[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdfa[39;00m [38;5;28;01mimport[39;00m DFA
[1;32m      3[0m A [38;5;241m=[39m [38;5;124m"[39m[38;5;124mA[39m[38;5;124m"[39m
[1;32m      4[0m B [38;5;241m=[39m [38;5;124m"[39m[38;5;124mB[39m[38;5;124m"[39m

[0;31mModuleNotFoundError[0m: No module named 'automata'

